version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: task-service-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: task-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tracker-network

volumes:
  postgres_data:

networks:
  tracker-network:
    driver: bridge